-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpaceShips
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SpaceShips` ;

-- -----------------------------------------------------
-- Schema SpaceShips
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpaceShips` DEFAULT CHARACTER SET utf8 ;
USE `SpaceShips` ;

-- -----------------------------------------------------
-- Table `SpaceShips`.`ship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SpaceShips`.`ship` ;

CREATE TABLE IF NOT EXISTS `SpaceShips`.`ship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `empire` ENUM('AMARR', 'CALDARI', 'MINMATAR', 'GALLENTE') NOT NULL DEFAULT 'AMARR',
  `type` ENUM('FRIGATE', 'CRUISER', 'BATTLECRUISER', 'BATTLESHIP') NOT NULL DEFAULT 'FRIGATE',
  `speed_warp` INT NULL DEFAULT 0,
  `speed_velocity` INT NULL DEFAULT 0,
  `time_to_warp` DECIMAL(10,2) NULL DEFAULT 0.0,
  `radar_range` DECIMAL(10,2) NULL DEFAULT 0.0,
  `cargo_capacity` INT UNSIGNED NULL DEFAULT 0,
  `mass` INT UNSIGNED NULL DEFAULT 0,
  `description` TEXT NULL,
  `cost` INT UNSIGNED NULL DEFAULT 0,
  `image` VARCHAR(1000) NULL DEFAULT 'http://games.chruker.dk/eve_online/graphics/ids/256/3117_2009.jpg',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS commander;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'commander' IDENTIFIED BY 'commander';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `SpaceShips`.* TO 'commander';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SpaceShips`.`ship`
-- -----------------------------------------------------
START TRANSACTION;
USE `SpaceShips`;
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (1, 'Crucifier', 'Amarr', 'Frigate', 5, 350, 4.94, 64, 265, 1064000, 'The Crucifier was first designed as an explorer/scout, but the current version employs the electronic equipment originally intended for scientific studies for more offensive purposes. The Crucifier\'s electronic and computer systems take up a large portion of the internal space leaving limited room for cargo or traditional weaponry.', 25000, 'https://wiki.eveuniversity.org/images/thumb/a/a2/Crucifier.jpg/256px-Crucifier.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (2, 'Thorax', 'Gallente', 'Cruiser', 3, 240, 7.66, 52.5, 465, 11280000, 'Some Text 2', 1500000, 'https://wiki.eveuniversity.org/images/thumb/8/89/Thorax.jpg/256px-Thorax.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (3, 'Megathron', 'Gallente', 'Battleship', 2, 122, 15.55, 87, 845, 98400000, 'The Thorax-class cruiser is the latest combat ship commissioned by the Federation. While the Thorax is a very effective ship at any range, typical of modern Gallente design philosophy it is most effective when working at extreme close range where its blasters and hordes of combat drones tear through even the toughest of enemies.', 60000000, 'https://wiki.eveuniversity.org/images/thumb/e/e4/Megathron.jpg/256px-Megathron.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (4, 'Punisher', 'Amarr', 'Frigate', 5, 355, 4.78, 25, 135, 1190000, 'The Punisher is considered by many to be one of the best Amarr frigates in existence. As evidenced by its heavy armaments, the Punisher is mainly intended for large-scale military operations, acting in coordination with larger military vessels. With its damage output, however, it is also perfectly capable of punching its way right through unwary opponents.', 40000, 'https://wiki.eveuniversity.org/images/thumb/0/0c/Punisher.jpg/256px-Punisher.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (5, 'Magnate', 'Amarr', 'Frigate', 5, 350, 5.65, 34, 400, 1072000, 'This Magnate-class frigate is one of the most decoratively designed ship classes in the Amarr Empire, considered to be a pet project for a small, elite group of royal ship engineers for over a decade. The frigate\'s design has gone through several stages over the past decade, and new models of the Magnate appear every few years. The most recent versions of this ship – the Silver Magnate and the Gold Magnate – debuted as rewards in the Amarr Championships in YC105, though the original Magnate design is still a popular choice among Amarr pilots.', 35000, 'https://wiki.eveuniversity.org/images/thumb/7/75/Magnate.jpg/256px-Magnate.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (6, 'Rifter', 'Minmatar', 'Frigate', 5, 365, 4.73, 22.5, 140, 1067000, 'The Rifter is a very powerful combat frigate and can easily tackle the best frigates out there. It has gone through many radical design phases since its inauguration during the Minmatar Rebellion. The Rifter has a wide variety of offensive capabilities, making it an unpredictable and deadly adversary.', 20000, 'https://wiki.eveuniversity.org/images/thumb/1/1e/Rifter.jpg/256px-Rifter.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (7, 'Merlin', 'Caldari', 'Frigate', 5, 310, 4.98, 50, 150, 997000, 'The Merlin is the most powerful combat frigate of the Caldari. Its role has evolved through the years, and while its defenses have always remained exceptionally strong for a Caldari vessel, its offensive capabilities have evolved from versatile, jack-of-all-trades attack patterns into focused and deadly gunfire tactics. The Merlin\'s primary aim is to have its turrets punch holes in opponents\' hulls.', 30000, 'https://wiki.eveuniversity.org/images/thumb/9/9d/Merlin.jpg/256px-Merlin.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (8, 'Heron', 'Caldari', 'Frigate', 5, 340, 5.69, 37.5, 400, 1150000, 'The Heron has good computer and electronic systems, giving it the option of participating in electronic warfare. But it has relatively poor defenses and limited weaponry, so it\'s more commonly used for scouting and exploration.', 35000, 'https://wiki.eveuniversity.org/images/thumb/f/f3/Heron.jpg/256px-Heron.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (9, 'Scythe', 'Minmatar', 'Cruiser', 3, 250, 9.24, 52.50, 475, 11110000, 'n YC114 each major empire faction, having been embroiled in a harrowing, extensive, long-term war, recognized the growing need for support and logistics functionality in their vessels during the kind of protracted interstellar warfare that might otherwise prove exhausting for its participants. Both Frigate and Cruiser-class ships were put under the microscope, and in the Minmatar Republic the outcome of the re-evaluation process led, among other developments, to a redesign and redeployment of the Scythe. The Scythe-class cruiser remains the oldest Minmatar ship still in use. It has seen many battles and is an integrated part in Minmatar tales and heritage. With its redesign, past firmware upgrades for mining output were tossed out entirely in favor of two new separate systems that focused on shield transporting and logistics drones respectively.', 3000000, 'https://wiki.eveuniversity.org/images/thumb/3/37/Scythe.jpg/256px-Scythe.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (10, 'Vexor', 'Gallente', 'Cruiser', 3, 195, 8.62, 52.50, 480, 11100000, 'The Vexor is a strong combat ship that is also geared to operate in a variety of other roles. The Vexor is especially useful for surveying in potentially hostile sectors as it can stay on duty for a very long time before having to return to base. Furthermore, it is well capable of defending itself against even concentrated attacks.', 4500000, 'https://wiki.eveuniversity.org/images/thumb/d/d9/Vexor.jpg/256px-Vexor.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (11, 'Arbitrator', 'Amarr', 'Cruiser', 3, 200, 8.69, 70, 345, 11200000, 'The Arbitrator is unusual for Amarr ships in that it\'s primarily a drone carrier. While it is not the best carrier around, it has superior armor that gives it greater durability than most ships in its class.', 5500000, 'https://wiki.eveuniversity.org/images/thumb/7/72/Arbitrator.jpg/256px-Arbitrator.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (12, 'Moa', 'Caldari', 'Cruiser', 3, 190, 8.65, 55, 450, 12000000, 'The Moa was designed as an all-out combat ship, and its heavy armament allows the Moa to tackle almost anything that floats in space. In contrast to its nemesis the Thorax, the Moa is most effective at long range where its railguns can rain death upon foes.', 3000000, 'https://wiki.eveuniversity.org/images/thumb/1/14/Moa.jpg/256px-Moa.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (13, 'Exequror', 'Gallente', 'Cruiser', 3, 240, 9.32, 55, 495, 11020000, 'In YC114 each major empire faction, having been embroiled in a harrowing, extensive, long-term war, recognized the growing need for support and logistics functionality in their vessels during the kind of protracted interstellar warfare that might otherwise prove exhausting for its participants. Both Frigate and Cruiser-class ships were put under the microscope, and in the Gallente Federation the outcome of the re-evaluation process led, among other developments, to a redesign and redeployment of the Exequoror. The Exequror was a heavy cargo cruiser originally strong enough to defend itself against raiding frigates, though it lacked prowess in heavier combat situations. After its redesign, it had some of that bulk - and, necessarily, some of that strength - yanked out and replaced with the capability to help others in heavy combat situations, in particular those who needed armor repairs.', 4150000, 'https://wiki.eveuniversity.org/images/thumb/6/62/Exequror.jpg/256px-Exequror.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (14, 'Caracal', 'Caldari', 'Cruiser', 3, 230, 7.76, 57.5, 450, 11910000, 'The Caracal is a powerful vessel that specializes in missile deployment. It has excellent shield defenses, but poor armor plating. Its missile arsenal, when fully stocked, is capable of making a piece-meal of almost anyone.', 5320000, 'https://wiki.eveuniversity.org/images/thumb/7/71/Caracal.jpg/256px-Caracal.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (15, 'Rupture', 'Minmatar', 'Cruiser', 3, 210, 8.46, 50, 450, 12200000, 'The Rupture is slow for a Minmatar ship, but it more than makes up for it in power. The Rupture has superior firepower and is used by the Minmatar Republic both to defend space stations and other stationary objects and as part of massive attack formations.', 2650000, 'https://wiki.eveuniversity.org/images/thumb/8/8b/Rupture.jpg/256px-Rupture.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (16, 'Abaddon', 'Amarr', 'Battleship', 2, 89, 20.03, 96, 740, 103200000, 'The Abaddon class ship is a celestial tool of destruction. It is designed to enter combat from the outset, targeting enemies at range and firing salvo after salvo at them, and to remain intact on the battlefield until every heretic in sight has been torn to shreds.', 76000000, 'https://wiki.eveuniversity.org/images/thumb/b/b7/Abaddon.jpg/256px-Abaddon.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (17, 'Dominix', 'Gallente', 'Battleship', 2, 109, 17.37, 84, 750, 100250000, 'The Dominix is one of the old warhorses dating back to the Gallente-Caldari War. While no longer regarded as the king of the hill, it is by no means obsolete. Its formidable hulk and powerful drone arsenal means that anyone not in the largest and latest battleships will regret ever locking horns with it.', 66500000, 'https://wiki.eveuniversity.org/images/thumb/e/e7/Dominix.jpg/256px-Dominix.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (18, 'Raven', 'Caldari', 'Battleship', 2, 113, 16.52, 90, 830, 99300000, 'The Raven is the powerhouse of the Caldari Navy. With its myriad launcher slots and powerful shields, few ships can rival it in strength or majesty.', 75000000, 'https://wiki.eveuniversity.org/images/thumb/9/9a/Raven.jpg/256px-Raven.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (19, 'Typhoon', 'Minmatar', 'Battleship', 2, 130, 15.34, 82.5, 780, 100600000, 'Much praised by its proponents and much maligned by its detractors, the Typhoon-class battleship has always been one of the most hotly debated spacefaring vessels around. Its distinguishing aspect - and the source of most of the controversy - is its sheer versatility, variously seen as either a lack of design focus or a deliberate freedom for pilot modification.', 53000000, 'https://wiki.eveuniversity.org/images/thumb/5/5f/Typhoon.jpg/256px-Typhoon.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (20, 'Tempest', 'Minmatar', 'Battleship', 2, 127, 16, 81, 780, 99500000, 'The Tempest is one of the Republic Fleet\'s key vessels; a versatile gunship proficient at long-range bombardment and capable of dishing out specialized types of damage with great effectiveness. A well-rounded squadron of Tempests has been proven time and time again to be an invaluable wild card in a fleet battle, one which opponents should ignore at their own peril.', 56500000, 'https://wiki.eveuniversity.org/images/thumb/4/46/Tempest.jpg/256px-Tempest.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (21, 'Brutix', 'Gallente', 'Battlecruiser', 3, 160, 11.12, 60, 475, 11800000, 'One of the most ferocious war vessels to ever spring from Gallente starship design, the Brutix is a behemoth in every sense of the word. When this hard-hitting monster appears, the battlefield takes notice.', 10500000, 'https://wiki.eveuniversity.org/images/thumb/1/12/Brutix.jpg/256px-Brutix.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (22, 'Hurricane', 'Minmatar', 'Battlecruiser', 3, 180, 11.89, 60, 425, 12800000, 'The force with which this ship hits is more than sufficient to leave a trail of shattered enemies, floating around like so much lifeless debris. An adaptable vessel, it has enough turret hardpoints for a full-scale assault while remaining versatile enough to allow for plenty of missile fire, and has both sufficient speed to outrun its enemies and sufficient capacitor charge to outlast them.', 15350000, 'https://wiki.eveuniversity.org/images/thumb/6/68/Hurricane.jpg/256px-Hurricane.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (23, 'Myrmidon', 'Gallente', 'Battlecruiser', 3, 145, 12.32, 55, 400, 12700000, 'Worried that their hot-shot pilots would burn brightly in their eagerness to engage the enemy, the Federation Navy created a ship that encourages caution over foolhardiness. A hardier version of its counterpart, the Myrmidon is a ship designed to persist in battle. Its numerous medium and high slots allow it to slowly bulldoze its way through the opposition, while its massive drone space ensures that no enemy is left unscathed.', 12500000, 'https://wiki.eveuniversity.org/images/thumb/4/40/Myrmidon.jpg/256px-Myrmidon.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (24, 'Naga', 'Caldari', 'Battlecruiser', 3, 195, 10.92, 75, 575, 15000000, 'The Naga was designed in YC 109 by Corporate Police Force as an anti-Guristas ship, sacrificing the usual robust Caldari Navy standards in favor of supporting battleship-class weaponry. It was rejected by Hyasyoda management for being overspecialized. The Naga design remained in the Hyasyoda archives, forgotten (save for a cameo in the Gallente holo-series CPF Blue). In YC 113 the Caldari Navy entertained contracts for a new tier of gunboat battlecruiser. Hyasyoda quickly submitted and won with the Naga, underbidding both Kaalakiota and Ishukone. The Naga is effective in any campaign where fast, mobile firepower is required.', 23050000, 'https://wiki.eveuniversity.org/images/thumb/b/b3/Naga.jpg/256px-Naga.jpg');
INSERT INTO `SpaceShips`.`ship` (`id`, `name`, `empire`, `type`, `speed_warp`, `speed_velocity`, `time_to_warp`, `radar_range`, `cargo_capacity`, `mass`, `description`, `cost`, `image`) VALUES (25, 'Oracle', 'Amarr', 'Battlecruiser', 3, 200, 10.13, 65, 500, 14760000, 'In YC 113 Empress Jamyl Sarum I challenged Amarr ship manufacturers to build a new battlecruiser that would break the stalemate of the Empyrean War. Deviating from the doctrine of brute-force and heavy armor, the engineers at Viziam took inspiration from Caldari history. During the Gallente-Caldari War, the Caldari developed light, maneuverable ships to counter the slow ships of the Gallente Federation. This philosophy, along with a cutting-edge powertrain and ultra-light alloy armor plating, led to the Oracle. The Empire immediately ordered the ship into production. The Empress personally congratulated Viziam Chief Researcher Parud Vakirokiki, calling the ship \"a work of Divine Grace for the Empire, and retribution to our enemies.”', 21550000, 'https://wiki.eveuniversity.org/images/thumb/9/97/Oracle.jpg/256px-Oracle.jpg');

COMMIT;

